"""All user-facing texts in Russian, Italian and English."""
from datetime import date

LANGUAGES = {"ru": "🇷🇺 Русский", "it": "🇮🇹 Italiano", "en": "🇬🇧 English"}

WEEKDAYS = {
    "ru": ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
    "it": ["Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom"],
    "en": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
}

TEXTS = {
    "ru": {
        "cmd_start": "Главное меню",
        "cmd_admin": "Панель владельца",
        "welcome": "👋 Здравствуйте! Это бот записи «{name}».\n\nВыберите действие:",
        "btn_book": "📅 Записаться",
        "btn_my": "📋 Мои записи",
        "btn_lang": "🌐 Язык",
        "btn_admin": "👑 Панель владельца",
        "btn_back": "⬅️ Назад",
        "btn_confirm": "✅ Подтвердить",
        "btn_yes_cancel": "✅ Да, отменить",
        "btn_cancel": "✖️ Отмена",
        "no_services": "Услуги пока не добавлены.",
        "choose_service": "Выберите услугу:",
        "choose_day": "Выберите день:",
        "choose_time": "{day}. Выберите время:",
        "no_days": "Свободных дней нет. Попробуйте позже.",
        "day_full": "На этот день свободного времени нет.",
        "check": "Проверьте запись:\n\n🔧 {service} — €{price}\n📅 {day}\n🕐 {time}",
        "booked": "✅ Вы записаны!\n\n🔧 {service}\n📅 {day} в {time}\n\n"
                  "Мы напомним о визите за день и за 2 часа.",
        "slot_taken": "😔 Это время уже заняли. Выберите другое.",
        "no_bookings": "У вас нет предстоящих записей.",
        "your_bookings": "Ваши записи:",
        "cancel_q": "Отменить запись?",
        "cancelled": "Запись отменена.",
        "not_found": "Запись не найдена.",
        "choose_lang": "Выберите язык:",
        "reminder": "🔔 Напоминание о записи\n\n🔧 {service}\n📅 {day} в {time}\n\n"
                    "Если не сможете прийти, отмените запись в разделе «Мои записи».",
        "cancelled_by_owner": "😔 Ваша запись отменена мастером:\n{service}, {day} в {time}.\n\n"
                              "Пожалуйста, выберите другое время.",
        "notify_new": "🆕 Новая запись\n\n🔧 {service} — €{price}\n📅 {day} в {time}\n👤 {client}",
        "notify_cancel": "❌ Клиент отменил запись\n\n🔧 {service}\n📅 {day} в {time}\n👤 {client}",
        "demo_note": "ℹ️ Демо-режим: такое уведомление получает владелец.",
        "booking_line": "• {service} — {day} {time}",
        "a_title": "👑 Панель владельца «{name}»",
        "a_bookings": "📅 Записи",
        "a_services": "🔧 Услуги",
        "a_schedule": "🕐 Расписание",
        "a_rename": "🏷 Название",
        "a_stats_btn": "📊 Статистика",
        "a_choose_day": "Выберите день (в скобках — число записей):",
        "a_day_title": "📅 {day}:",
        "a_day_empty": "📅 {day}: записей нет.",
        "a_line": "{time} — {service} — {client}",
        "a_services_title": "Услуги:",
        "a_services_empty": "Услуг пока нет.",
        "a_add_service": "➕ Добавить услугу",
        "a_ask_service": "Введите название услуги:",
        "a_bad_service": "Название должно быть от 1 до 50 символов.",
        "a_ask_price": "Введите цену для «{service}» в евро, например 30:",
        "a_bad_price": "Нужно целое число от 0 до 100000, например 30.",
        "a_service_added": "Услуга «{service}» добавлена ✅",
        "a_schedule_text": "🕐 Время приёма: {slots}\n🚫 Выходные: {days_off}\n"
                           "📆 Запись открыта на {ahead} дн. вперёд",
        "a_edit_slots": "🕐 Изменить время",
        "a_edit_days_off": "🚫 Выходные дни",
        "a_ahead": "{n} дн.",
        "a_ask_slots": "Отправьте время приёма через пробел, например:\n10:00 11:00 12:00 15:00 16:00",
        "a_bad_slots": "Не понял формат. Пример: 10:00 11:30 15:00",
        "a_days_off_text": "Нажмите на день, чтобы сделать его рабочим или выходным:",
        "a_ask_name": "Введите новое название бизнеса:",
        "a_bad_name": "Название должно быть от 1 до 60 символов.",
        "a_saved": "Сохранено ✅",
        "a_cancel_q": "Отменить эту запись? Клиент получит уведомление.\n\n📅 {day}\n{line}",
        "a_cancel_done": "Запись отменена, клиент уведомлён.",
        "a_stats": "📊 Статистика\n\nЗа 7 дней: {week_n} записей, €{week_sum}\n"
                   "За 30 дней: {month_n} записей, €{month_sum}\n"
                   "Предстоящих записей: {upcoming}\nПопулярная услуга: {top}",
        "none": "—",
    },
    "it": {
        "cmd_start": "Menu principale",
        "cmd_admin": "Pannello del titolare",
        "welcome": "👋 Benvenuto! Questo è il bot di prenotazione di «{name}».\n\nScegli un'azione:",
        "btn_book": "📅 Prenota",
        "btn_my": "📋 Le mie prenotazioni",
        "btn_lang": "🌐 Lingua",
        "btn_admin": "👑 Pannello del titolare",
        "btn_back": "⬅️ Indietro",
        "btn_confirm": "✅ Conferma",
        "btn_yes_cancel": "✅ Sì, annulla",
        "btn_cancel": "✖️ Annulla",
        "no_services": "Non ci sono ancora servizi.",
        "choose_service": "Scegli un servizio:",
        "choose_day": "Scegli il giorno:",
        "choose_time": "{day}. Scegli l'orario:",
        "no_days": "Non ci sono giorni liberi. Riprova più tardi.",
        "day_full": "Non ci sono orari liberi per questo giorno.",
        "check": "Controlla la prenotazione:\n\n🔧 {service} — €{price}\n📅 {day}\n🕐 {time}",
        "booked": "✅ Prenotazione confermata!\n\n🔧 {service}\n📅 {day} alle {time}\n\n"
                  "Ti ricorderemo l'appuntamento il giorno prima e 2 ore prima.",
        "slot_taken": "😔 Questo orario è appena stato preso. Scegline un altro.",
        "no_bookings": "Non hai prenotazioni in programma.",
        "your_bookings": "Le tue prenotazioni:",
        "cancel_q": "Vuoi annullare la prenotazione?",
        "cancelled": "Prenotazione annullata.",
        "not_found": "Prenotazione non trovata.",
        "choose_lang": "Scegli la lingua:",
        "reminder": "🔔 Promemoria appuntamento\n\n🔧 {service}\n📅 {day} alle {time}\n\n"
                    "Se non puoi venire, annulla la prenotazione in «Le mie prenotazioni».",
        "cancelled_by_owner": "😔 La tua prenotazione è stata annullata dal titolare:\n"
                              "{service}, {day} alle {time}.\n\nTi preghiamo di scegliere un altro orario.",
        "notify_new": "🆕 Nuova prenotazione\n\n🔧 {service} — €{price}\n📅 {day} alle {time}\n👤 {client}",
        "notify_cancel": "❌ Il cliente ha annullato\n\n🔧 {service}\n📅 {day} alle {time}\n👤 {client}",
        "demo_note": "ℹ️ Modalità demo: questa è la notifica che riceve il titolare.",
        "booking_line": "• {service} — {day} {time}",
        "a_title": "👑 Pannello del titolare «{name}»",
        "a_bookings": "📅 Prenotazioni",
        "a_services": "🔧 Servizi",
        "a_schedule": "🕐 Orari",
        "a_rename": "🏷 Nome attività",
        "a_stats_btn": "📊 Statistiche",
        "a_choose_day": "Scegli il giorno (tra parentesi il numero di prenotazioni):",
        "a_day_title": "📅 {day}:",
        "a_day_empty": "📅 {day}: nessuna prenotazione.",
        "a_line": "{time} — {service} — {client}",
        "a_services_title": "Servizi:",
        "a_services_empty": "Nessun servizio.",
        "a_add_service": "➕ Aggiungi servizio",
        "a_ask_service": "Scrivi il nome del servizio:",
        "a_bad_service": "Il nome deve avere da 1 a 50 caratteri.",
        "a_ask_price": "Scrivi il prezzo di «{service}» in euro, ad esempio 30:",
        "a_bad_price": "Serve un numero intero da 0 a 100000, ad esempio 30.",
        "a_service_added": "Servizio «{service}» aggiunto ✅",
        "a_schedule_text": "🕐 Orari: {slots}\n🚫 Giorni di chiusura: {days_off}\n"
                           "📆 Prenotazioni aperte per {ahead} giorni",
        "a_edit_slots": "🕐 Modifica orari",
        "a_edit_days_off": "🚫 Giorni di chiusura",
        "a_ahead": "{n} gg",
        "a_ask_slots": "Invia gli orari separati da spazi, ad esempio:\n10:00 11:00 12:00 15:00 16:00",
        "a_bad_slots": "Formato non valido. Esempio: 10:00 11:30 15:00",
        "a_days_off_text": "Tocca un giorno per renderlo lavorativo o di chiusura:",
        "a_ask_name": "Scrivi il nuovo nome dell'attività:",
        "a_bad_name": "Il nome deve avere da 1 a 60 caratteri.",
        "a_saved": "Salvato ✅",
        "a_cancel_q": "Annullare questa prenotazione? Il cliente riceverà una notifica.\n\n📅 {day}\n{line}",
        "a_cancel_done": "Prenotazione annullata, il cliente è stato avvisato.",
        "a_stats": "📊 Statistiche\n\nUltimi 7 giorni: {week_n} prenotazioni, €{week_sum}\n"
                   "Ultimi 30 giorni: {month_n} prenotazioni, €{month_sum}\n"
                   "In programma: {upcoming}\nServizio più richiesto: {top}",
        "none": "—",
    },
    "en": {
        "cmd_start": "Main menu",
        "cmd_admin": "Owner panel",
        "welcome": "👋 Hello! This is the booking bot of «{name}».\n\nChoose an action:",
        "btn_book": "📅 Book",
        "btn_my": "📋 My bookings",
        "btn_lang": "🌐 Language",
        "btn_admin": "👑 Owner panel",
        "btn_back": "⬅️ Back",
        "btn_confirm": "✅ Confirm",
        "btn_yes_cancel": "✅ Yes, cancel",
        "btn_cancel": "✖️ Cancel",
        "no_services": "No services yet.",
        "choose_service": "Choose a service:",
        "choose_day": "Choose a day:",
        "choose_time": "{day}. Choose a time:",
        "no_days": "No free days. Please try later.",
        "day_full": "No free time on this day.",
        "check": "Check your booking:\n\n🔧 {service} — €{price}\n📅 {day}\n🕐 {time}",
        "booked": "✅ You're booked!\n\n🔧 {service}\n📅 {day} at {time}\n\n"
                  "We'll remind you a day before and 2 hours before.",
        "slot_taken": "😔 This time was just taken. Please choose another one.",
        "no_bookings": "You have no upcoming bookings.",
        "your_bookings": "Your bookings:",
        "cancel_q": "Cancel this booking?",
        "cancelled": "Booking cancelled.",
        "not_found": "Booking not found.",
        "choose_lang": "Choose a language:",
        "reminder": "🔔 Appointment reminder\n\n🔧 {service}\n📅 {day} at {time}\n\n"
                    "If you can't come, please cancel it in «My bookings».",
        "cancelled_by_owner": "😔 Your booking was cancelled by the owner:\n{service}, {day} at {time}.\n\n"
                              "Please choose another time.",
        "notify_new": "🆕 New booking\n\n🔧 {service} — €{price}\n📅 {day} at {time}\n👤 {client}",
        "notify_cancel": "❌ Client cancelled\n\n🔧 {service}\n📅 {day} at {time}\n👤 {client}",
        "demo_note": "ℹ️ Demo mode: this is the notification the owner receives.",
        "booking_line": "• {service} — {day} {time}",
        "a_title": "👑 Owner panel «{name}»",
        "a_bookings": "📅 Bookings",
        "a_services": "🔧 Services",
        "a_schedule": "🕐 Schedule",
        "a_rename": "🏷 Business name",
        "a_stats_btn": "📊 Statistics",
        "a_choose_day": "Choose a day (number of bookings in brackets):",
        "a_day_title": "📅 {day}:",
        "a_day_empty": "📅 {day}: no bookings.",
        "a_line": "{time} — {service} — {client}",
        "a_services_title": "Services:",
        "a_services_empty": "No services yet.",
        "a_add_service": "➕ Add service",
        "a_ask_service": "Enter the service name:",
        "a_bad_service": "The name must be 1 to 50 characters long.",
        "a_ask_price": "Enter the price of «{service}» in euros, e.g. 30:",
        "a_bad_price": "Please enter a whole number from 0 to 100000, e.g. 30.",
        "a_service_added": "Service «{service}» added ✅",
        "a_schedule_text": "🕐 Hours: {slots}\n🚫 Days off: {days_off}\n📆 Booking open {ahead} days ahead",
        "a_edit_slots": "🕐 Edit hours",
        "a_edit_days_off": "🚫 Days off",
        "a_ahead": "{n} days",
        "a_ask_slots": "Send the time slots separated by spaces, e.g.:\n10:00 11:00 12:00 15:00 16:00",
        "a_bad_slots": "Wrong format. Example: 10:00 11:30 15:00",
        "a_days_off_text": "Tap a day to make it a working day or a day off:",
        "a_ask_name": "Enter the new business name:",
        "a_bad_name": "The name must be 1 to 60 characters long.",
        "a_saved": "Saved ✅",
        "a_cancel_q": "Cancel this booking? The client will be notified.\n\n📅 {day}\n{line}",
        "a_cancel_done": "Booking cancelled, the client has been notified.",
        "a_stats": "📊 Statistics\n\nLast 7 days: {week_n} bookings, €{week_sum}\n"
                   "Last 30 days: {month_n} bookings, €{month_sum}\n"
                   "Upcoming: {upcoming}\nMost popular service: {top}",
        "none": "—",
    },
}


def t(lang, key, **kwargs):
    return TEXTS.get(lang, TEXTS["en"])[key].format(**kwargs)


def fmt_day(day, lang):
    d = date.fromisoformat(day)
    return f"{WEEKDAYS.get(lang, WEEKDAYS['en'])[d.weekday()]} {d:%d.%m}"
